package com.honeydewit;

public class Constants {
	public static final Integer TRUE = 1;
	public static final Integer FALSE = 0;
	public static final String DIALOG_SINGLE_INPUT = "newListName";
	public static final String LIST_HOME_PREFS = "preferences";
	public static final int dateTimeReminderRequest = 0;
	public static final int TIME_PICKER_RESULT_CODE = 0;
	public static final int DATE_PICKER_RESULT_CODE = 1;
	public static final String RESULT_CODE = "resultCode";
	public static final String RESULT = "result";
	public static final Integer REQ_CALENDAR_CDE = 1;
	public static final Integer REQ_LIST_EVENTS = 2;
	public static final Integer RESPONSE_ERROR = 1;
	public static final Integer RESULT_EVENT_SAVED = 7;
	public static final String NO_SUBJECT = "{No Subject}";
	public static final Integer TODO_LIST_TYPE_CDE = 2;
	public static final Integer SHOPPING_LIST_TYPE_CDE = 1;
	public static final String LIST_TYPE = "listType";
	public static final String SUB_CAT_CODE = "subCatCode";
	public static final String LOG_FILE_EXT = ".log.html";
	public static final String HIDE_IMPORTING_MESSAGE = "hideImportingMessage";
	public static final String SPLIT = "\\^";
	public static final String STRING_REPLACE_CHAR = "^";
	public static final String EMPTY_STRING = "";
	public static final String PREV_ACTIVITY = "previousActivity";
	public static final String LIST_INFO = "listInfo";
	public static final Integer NOTES_LIST_TYP_CODE = 6;
	public static final int CHECKBOX_DIALOG_REQUEST_CODE = 9;
	public static final int CHECKBOX_DIALOG_FINISH_RESULT_CODE = 10;
	public static final int RESULT_FINISH = 13;
	public static final int RESULT_REPLACE = 14;
	public static final String XLS_EXT = ".xls";
	public static final String XLSX_EXT = ".xlsx";
	public static final String TXT_EXT = ".txt";
	public static final String CSV_EXT = ".csv";
	public static final String XML_EXT = ".xml";
	public static final String HDEW_EXT = ".hdew";
	public static final String XML_MIME = "text/xml";
	public static final String CSV_MIME = "text/csv";
	public static final String TEXT_MIME = "text/plain";
	public static final String APPLICATION_OCTET_MIME = "application/octet-stream";
	public static final String OPEN_OFFICE_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
	public static final int EXCEL_CHECK_REQ = 123;
	public static final int XML_CHECK_REQ = 124;
	public static final int TEXT_CHECK_REQ = 125;
	public static final int SHEET_REPLACE_REQ = 232;
	public static final int REQUEST_IMAGE_CAPTURE = 1;
	public static final int REQUEST_TAKE_PHOTO = 1;
	public static final String SHOW_HOME_SPLASH_SCREEN = "showSplashHome";
	public static final String IMAGE_NAME = "imageName";
	public static final int ITEM_TYPE_REQUEST = 2;
    public static final int LIST_NAME_CHOICE_REQ_CODE = 0;
	public static final String CALC_TYPE = "calcType";
	public static final int RESULT_QTY = 1;
	public static final int RESULT_UNIT_PRICE = 1;
	public static final int REQUEST_CALCULATOR = 1235;
	public static final String JPEG = ".jpeg";
	public static final String LIST_ITEM = "listItem";


}
